# Generated by Django 4.1.2 on 2022-10-08 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('province', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('postalCode', models.CharField(max_length=7)),
                ('streetNumber', models.CharField(max_length=45)),
                ('streetName', models.CharField(max_length=45)),
                ('unitNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('dailyCost', models.FloatField()),
                ('weeklyCost', models.FloatField()),
                ('monthlyCost', models.FloatField()),
                ('lateFee', models.FloatField()),
                ('changeBranchFee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('driverLicense', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=45)),
                ('dob', models.DateField()),
                ('goldMembership', models.CharField(max_length=45)),
                ('province', models.CharField(max_length=45)),
                ('postalCode', models.CharField(max_length=7)),
                ('streetNumber', models.CharField(max_length=45)),
                ('streetName', models.CharField(max_length=45)),
                ('unitNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('province', models.CharField(max_length=45)),
                ('postalCode', models.CharField(max_length=7)),
                ('streetNumber', models.CharField(max_length=45)),
                ('streetName', models.CharField(max_length=45)),
                ('unitNumber', models.IntegerField()),
                ('branchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.branch')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='colour',
            field=models.CharField(default=99, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuelType',
            field=models.CharField(default=99, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='licensePlate',
            field=models.CharField(default=99, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(default=99, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default=99, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=45),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('dateReturned', models.DateField()),
                ('totalCost', models.FloatField()),
                ('licensePlate', models.CharField(max_length=45)),
                ('goldMembership', models.CharField(max_length=45)),
                ('branchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.branch')),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.car')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.customer')),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.employee')),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.cartype')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='BranchID',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='car_rental.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='typeID',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='car_rental.cartype'),
            preserve_default=False,
        ),
    ]
