# Generated by Django 4.1.2 on 2022-10-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_branch_cartype_customer_employee_car_colour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='BranchID',
        ),
        migrations.RemoveField(
            model_name='car',
            name='typeID',
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
